---
title: "Final Project Code"
author: "Kunwu Lyu and Evan Hart"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(ordinal)
library(VGAM)
library(stringr)
library(tidymodels)
library(optimx)
library(car)
library(workflows)
```

## Data Wrangling

```{r}
survey <- read_tsv("data/ICPSR_37143/DS0001/37143-0001-Data.tsv") %>%
  janitor::clean_names()
receipt <- read_tsv("data/ICPSR_37143/DS0002/37143-0002-Data.tsv") %>%
  janitor::clean_names()
fast_food <- read_tsv("data/ICPSR_37143/DS0003/37143-0003-Data.tsv") %>%
  janitor::clean_names()
grocery <- read_tsv("data/ICPSR_37143/DS0004/37143-0004-Data.tsv") %>%
  janitor::clean_names()
recall <- read_tsv("data/ICPSR_37143/DS0005/37143-0005-Data.tsv") %>%
  janitor::clean_names()

full_data <- survey %>%
  full_join(receipt, relationship = "many-to-many") %>%  
  full_join(fast_food, relationship = "many-to-many") %>%
  full_join(grocery, relationship = "many-to-many") %>%
  full_join(recall, relationship = "many-to-many") 

full_data <- full_data %>% 
  mutate(limit = ordered(q75, levels = c("Never", "Seldom", "Sometimes", "Often", "Always"))) %>% 
  mutate(age = as.numeric(q76) - mean(as.numeric(76)),
         gender = if_else(q77 == 0, "M", "F"),
         race = case_when(
           !is.na(q79_1) ~ "Native",
           !is.na(q79_2) ~ "Black",
           !is.na(q79_3) ~ "Asian",
           !is.na(q79_4) ~ "White",
           !is.na(q79_a) ~ "Other"
         ),
         edu = as.numeric(q80),
         location = nemslocationindicator,
         city = q1,
         num_kids = q44,
         surveydate = dmy(surveydate)) %>%
  mutate(days_since_ban = as.numeric(interval(as.Date("2013-03-12"), surveydate) / days(1))) 

standardize <- function(x, na.rm = TRUE) {
  (x - mean(x, na.rm = na.rm)) / 
    sd(x, na.rm = na.rm)
}

reduced_data <- full_data %>% 
  mutate(age_std = standardize(as.numeric(q76))) %>%
  select(c("receiptid", "person_id", "limit", "age", "age_std", "gender", "race", "edu", "city", "caff", "location", "round", "nsigns_ssb", "num_kids", "surveydate", "days_since_ban", "kcal", "f_total", "v_total")) %>%
  group_by(receiptid) %>% 
  mutate(caff = mean(caff, na.rm = T),
         f_total = mean(f_total, na.rm = T),
         v_total = mean(v_total, na.rm = T),
         kcal = mean(kcal, na.rm = T)) %>% 
  drop_na() %>% 
  distinct() %>% 
  mutate(receiptid = as.factor(receiptid),
         person_id = as.factor(person_id),
         location = as.factor(location),
         round = as.factor(round),
         edu = case_when(
           edu == 1 ~ "Less than High School",
           edu == 2 ~ "Some High School",
           edu == 3 ~ "High School",
           edu == 4 ~ "Some College",
           edu == 5 ~ "Associates Degree",
           edu == 6 ~ "College Degree",
           edu == 7 ~ "Graduate Degree"
         )) %>% 
  ungroup() %>% 
  mutate(f_std = standardize(f_total),
         v_std = standardize(v_total),
         caff_std = standardize(caff),
         nsigns_ssb_std = standardize(nsigns_ssb),
         days_since_ban_std = standardize(days_since_ban),
         kcal_std = standardize(kcal)
         ) %>% 
  mutate(fv = f_std + v_std) %>% 
  mutate(fv_std = standardize(fv))

write_csv(reduced_data, "dietControl.csv")

multi_round_locations <- reduced_data %>%
  group_by(receiptid) %>% 
  summarize(n_rounds = n_distinct(round)) %>% 
  filter(n_rounds > 1) %>%
  pull(receiptid)

reduced_data %>%
  filter(location %in% multi_round_locations) %>%
  count(receiptid, location)
```


### Kunwu's section

```{r Optimization Methods, cache=TRUE, eval=T}
control_clm_full <- clm(limit ~ 1 + age + gender + race + edu + caff + nsigns_ssb + num_kids + days_since_ban, 
                   data = reduced_data, control = list(
  maxIter = 10000, 
  maxLineIter = 2000, 
  maxModIter = 2000, 
  method = "Newton", 
  trace = 1))
control_clm <- clm(limit ~ 1 + age + gender + race + edu + caff + nsigns_ssb + num_kids + days_since_ban, data = reduced_data, control = list(
  method = "ucminf",
  stepmax = 1,
  grad = "central",
  maxeval = 500000,
  gradstep = c(1e-10, 1e-12),
  trace = 1))
control_clm <- clm(limit ~ 1 + age + gender + race + edu + caff + nsigns_ssb + num_kids + days_since_ban, data = reduced_data, control = list(
  method = "nlminb",
  eval.max = 2000,
  iter.max = 1500,
  abs.tol = 1e-20,
  trace = 1))
control_clm <- clm(limit ~ 1 + age + gender + race + edu + caff + nsigns_ssb + num_kids + days_since_ban, data = reduced_data, control = list(
  method = "optim",
  tmax = 100,
  maxit = 100000,
  type = 1,
  ndeps = 1e-10,
  REPORT = 1,
  trace = 1))
control_vglm <- vglm(limit ~ 1 + age + gender + race + edu + caff + nsigns_ssb + num_kids + days_since_ban, 
                     data = reduced_data, family = cumulative(parallel = TRUE))
control_clmm_full <- clmm(limit ~ 1 + age + gender + race + edu + city + caff + nsigns_ssb + num_kids + days_since_ban + (1 | location) + (1 | round), 
                          control = list(method = "nlminb",
                                         useMatrix = T,
                                         maxIter = 200, 
                                         gradTol = 1e-4, 
                                         maxLineIter = 200,
                                         trace = 1),
                     data = reduced_data, link = "logit")

summary(control_clm)
summary(control_vglm)
coef(control_vglm, matrix = T)
summary(control_clmm_full)
coef(control_clmm_full, matrix = T)
```

```{r}
control_clmm_full_std <- clmm(limit ~ 1 + age_std + gender + race + edu + city + caff_std + nsigns_ssb_std + num_kids + days_since_ban_std + kcal_std + fv_std + (1 | location) + (1 | round), 
                          control = list(method = "nlminb",
                                         useMatrix = T,
                                         maxIter = 200, 
                                         gradTol = 1e-4, 
                                         maxLineIter = 200,
                                         trace = 1),
                     data = reduced_data, link = "logit")
control_clmm_full_non <- clmm(limit ~ 1 + age + gender + race + edu + city + caff + nsigns_ssb + num_kids + days_since_ban + kcal + fv + (1 | location) + (1 | round), 
                          control = list(method = "nlminb",
                                         useMatrix = T,
                                         maxIter = 200, 
                                         gradTol = 1e-4, 
                                         maxLineIter = 200,
                                         trace = 1),
                     data = reduced_data, link = "logit")
summary(control_clmm_full_std)
```


```{r Model Selection, cache=TRUE}
control_clmm_red <- clmm(limit ~ 1 + age_std + gender + edu + num_kids + (1 | location) + (1 | round), control = list(trace = 1),
                     data = reduced_data, link = "logit")
anova(control_clmm_red, control_clmm_full_std)
summary(control_clmm_red)


control_clmm_loc <- clmm(limit ~ 1 + age_std + gender + edu + num_kids + (1 | location), control = list(trace = 1),
                     data = reduced_data, link = "logit")

lrt_obs_round <- as.numeric(2*(logLik(control_clmm_red) - logLik(control_clmm_loc)))
.5*(1 - pchisq(lrt_obs_round, 0)) + .5*(1 - pchisq(lrt_obs_round, 1))

control_clm <- clm(limit ~ 1 + age_std + gender + edu + num_kids, control = list(trace = 1),
                     data = reduced_data, link = "logit")
lrt_obs_loc <- as.numeric(2*(logLik(control_clmm_loc) - logLik(control_clm)))
.5*(1 - pchisq(lrt_obs_loc, 0)) + .5*(1 - pchisq(lrt_obs_loc, 1))

summary(control_clm)
control_null <- clm(limit ~ 1, data = reduced_data, link = "logit")
# Overall fit
anova(control_null, control_clm)
```


```{r Bootstrap, eval=FALSE}
set.seed(54185214)

Nsim <- 1000   
lrt_sim <- rep(NA,Nsim) 

nullY <- simulate(control_clmm_loc, nsim=Nsim)

for (i in 1:Nsim){  
  null_clmm <- clmm(nullY[ , i] ~ 1 + age + gender + edu + num_kids + (1 | location),
       data = reduced_data, link = "logit")
  alt_clmm <- refit(control_clmm_red, nullY[, i])
  lrt_sim[i] <- 2*(logLik(alt_clmm, REML = TRUE)-logLik(null_clmm, REML = TRUE))
}

mean(lrt_sim > lrt_obs_round)       #P-value
ggplot(data.frame(lrt_sim), aes(x=lrt_sim)) + 
  geom_histogram(color = "white") + 
  geom_vline(xintercept = lrt_obs_round, color = "red") 
```


```{r Model Accuracy, cache=TRUE}
control_pred <- predict(control_clm, type = "class")
control_results <- reduced_data %>%
  bind_cols(predicted = control_pred)
# table(control_results$limit, control_results$fit)
conf_mat(control_results, truth = limit, estimate = fit)

# Goodness of fit
chisq.test(control_results$limit, control_results$fit)

accuracy(control_results, truth = limit, estimate = fit)
sensitivity(control_results, truth = limit, estimate = fit)
specificity(control_results, truth = limit, estimate = fit)
# ppv(control_results, truth = limit, estimate = fit)
```

```{r Residual Analysis}
plot(fitted(control_clm), residuals(control_clm))

control_resid <- control_results %>%
  mutate(
    case_id = row_number(), 
    fit = ordered(fit, levels = c("Never", "Seldom", "Sometimes", "Often", "Always"))
  ) %>% 
  select(case_id, limit, fit)

ggplot(control_resid, aes(x = case_id)) +
  geom_point(aes(y = limit, color = "Actual"), alpha = 0.7) +
  geom_point(aes(y = fit, color = "Fitted"), alpha = 0.7) +
  scale_color_manual(values = c("Actual" = "blue", "Fitted" = "red")) +
  labs(
    x = "Case ID",
    y = "Response Category",
    title = "Actual vs. Fitted Values",
    color = "Legend"
  ) +
  theme_minimal()
```

### Evan's section

```{r}
# Single variables w/ limit

# Age
ggplot(data = reduced_data, aes(x = age , y = limit)) + 
  geom_boxplot() +
  labs(x = "age", y = "Limit")

# Age faceted by gender
ggplot(data = reduced_data, aes(x = age , y = limit)) + 
  geom_boxplot() +
  facet_wrap(~gender) +
  labs(x = "age", y = "Limit")

# Child count
ggplot(data = reduced_data, aes(x = num_kids, fill = limit)) +
  geom_bar(position = "fill") + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x = "Child Count", y = "Percentage", fill = "Limit") +
  theme_minimal()


ggplot(data = reduced_data, aes(x = num_kids, fill = limit)) +
  geom_bar(position = "fill") + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x = "Child Count", y = "Percentage", fill = "Limit") +
  facet_wrap(~gender) +
  theme_minimal()


# Race
ggplot(data = reduced_data, aes(x = race, fill = limit)) +
  geom_bar(position = "fill") + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x = "Race", y = "Percentage", fill = "Limit") +
  theme_minimal()

# Education
ggplot(data = reduced_data, aes(x = edu, fill = limit)) +
  geom_bar(position = "fill") + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x = "Education", y = "Percentage", fill = "Limit") +
  theme_minimal()

# City
ggplot(data = reduced_data, aes(x = city, fill = limit)) +
  geom_bar(position = "fill") + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x = "City", y = "Percentage", fill = "Limit") +
  theme_minimal()

# Caffeine
ggplot(data = reduced_data %>% filter(caff > 0), aes(x = log(caff + 1) , y = limit)) + 
  geom_boxplot() +
  labs(x = "Caffeine", y = "Limit")

# Survey round
ggplot(data = reduced_data, aes(x = round, fill = limit)) +
  geom_bar(position = "fill") + 
  scale_y_continuous(labels = scales::percent) + 
  labs(x = "Round", y = "Percentage", fill = "Limit") +
  facet_wrap(~city) +
  theme_minimal()

# Advertisement count
ggplot(data = reduced_data, aes(y = nsigns_ssb, x = limit)) +
  geom_boxplot() + 
  labs(y = "Advertisement Count", x = "Limit") +
  theme_minimal()
```

```{r}
# Plot function for interactions

plot_cats <- c("limit", "gender", "race", "city", "round", "num_kids", "edu", "diet")
plot_nums <- c("age", "caff", "nsigns_ssb", "days_since_ban")

library(rlang)

make_plot <- function(var1, var2){
  if(var1 %in% plot_cats & var2 %in% plot_cats){
    print(ret_plot <- ggplot(data =reduced_data, aes(x = !!sym(var1), fill = !!sym(var2))) +
      geom_bar(position = "fill") + 
      scale_y_continuous(labels = scales::percent) + 
      theme_minimal())
  }
  
  if(var1 %in% plot_cats & var2 %in% plot_nums){
    print(ret_plot <- ggplot(data = reduced_data, aes(x = !!sym(var1), y = !!sym(var2))) +
      geom_boxplot() + 
      theme_minimal())
  }
  
  if(var1 %in% plot_nums & var2 %in% plot_cats){
    print(ret_plot <- ggplot(data = reduced_data, aes(x = !!sym(var2), y = !!sym(var1))) + 
       geom_boxplot() + 
       theme_minimal())
  }
  
  if(var1 %in% plot_nums & var2 %in% plot_nums){
    print(ggplot(data = reduced_data, aes(x = !!sym(var2), y = !!sym(var1))) +
      geom_point() +
      theme_minimal())
  }
}
```

```{r}
for(i in 1:length(names(reduced_data))){
  if(i != length(reduced_data)){
    for(j in (i+1):length(reduced_data)){
      make_plot(names(reduced_data)[i], names(reduced_data)[j])
    }
  }
}
```






